openapi: 3.0.1
info:
  title: Nexus Terraform Provider
  x-cortex-tag: platform-tooling/nexus/terraform-provider
  x-cortex-type: service
  description: Terraform provider to configure Sonatype Nexus using its API
  x-cortex-git:
    github:
      repository: octoenergy/terraform-provider-nexus
      alias: octoenergy
  x-cortex-slack:
    channels:
    - id: C0853EG15S7
      description: x-internal-channel
      notificationsEnabled: false
    - id: C0853HWRHKL
      description: x-monitoring-alerts-channel
      notificationsEnabled: true
  x-cortex-groups:
    - services
    - platform
    - platform-experience
    - nexus
  x-cortex-owners:
  - name: team-platform-experience
    type: group
    provider: CORTEX
  x-cortex-relationships:
  - type: ktl-product-hierarchy
    sources:
    - tag: platform-tooling/nexus
  - type: ktl-client-hierarchy
    sources:
      - tag: clients/kraken-tech
  x-cortex-link:
    - name: Runbook
      type: RUNBOOK
      url: https://www.notion.so/kraken-tech/User-Guides-c0346657738c48e99bfc4985e72c028a?source=copy_link
    - name: Documentation
      type: documentation
      url: https://www.notion.so/kraken-tech/Nexus-Repository-Manager-870ce6925718468e9ffe1ca4e87e3e00?source=copy_link
  x-cortex-custom-metadata:
    data-classification:
      value: Internal
      description: "Confidential, Internal or Public. See OEGL Information Classification\
        \ policy for further details: https://drive.google.com/drive/folders/1L8z2mtWjcv3SIOJWr7K2Whcr39vkFg5c"
    risk-profile:
      value: Moderate
      description: ""
